// <auto-generated />
using CommandApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommandApi.Migrations
{
    [DbContext(typeof(CommandContext))]
    [Migration("20221209143932_AddInitialData")]
    partial class AddInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommandApi.Models.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HowTo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommandItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommandLine = "dotnet ef migrations add <Name of Migration>",
                            HowTo = "How to generate a migration",
                            Platform = ".Net Core EF Command line"
                        },
                        new
                        {
                            Id = 2,
                            CommandLine = "dotnet ef database update",
                            HowTo = "Run Migrations",
                            Platform = ".Net Core EF Command line"
                        },
                        new
                        {
                            Id = 3,
                            CommandLine = "add-migration <Name of Migration>",
                            HowTo = "How to generate a migration",
                            Platform = "EF Package Manager Console"
                        },
                        new
                        {
                            Id = 4,
                            CommandLine = "database update",
                            HowTo = "Run Migrations",
                            Platform = "EF Package Manager Console"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
